\c bookie_dev;

INSERT INTO
    books( title , author, publisher , published_year , pages , genre , art , description)
VALUES
    ('Meditations', 'Marcus', 'Simon & Brown', 2016, 108, 'Philosophy', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/MeditationsMarcusAurelius1811.jpg/640px-MeditationsMarcusAurelius1811.jpg', 'In the Meditations, Marcus Aurelius places a great deal of emphasis on the pursuit of wisdom and virtue as the ultimate goals of human life. Many of the Stoics viewed virtue as the only good and believed that to live a good and happy life, virtue must be at the top of the list of priorities.'),
    ('1984', 'George Orwell', 'Secker & Warburg', 1949, 108, 'Dystopian', 'https://upload.wikimedia.org/wikipedia/en/5/51/1984_first_edition_cover.jpg', '1984 is the story of a man questioning the system that keeps his futuristic but dystopian society afloat and the chaos that quickly ensues once he gives in to his natural curiosity and desire to be free.'),
    ('To Kill a Mockingbird', 'Harper Lee', 'J. B. Lippincott & Co.', 1960, 281, 'Bildungsroman', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg/440px-To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg', 'To Kill a Mockingbird is both a young girls coming-of-age story and a darker drama about the roots and consequences of racism and prejudice, probing how good and evil can coexist within a single community or individual.'),
    ('The Great Gatsby', 'F. Scott Fitzgerald', 'Charles Scribners Sons', 1925, 108, 'Tradgedy', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg/440px-The_Great_Gatsby_Cover_1925_Retouched.jpg', 'The Great Gatsby tells the tragic story of Jay Gatsby, a self-made millionaire, and his pursuit of Daisy Buchanan, a wealthy young woman whom he loved in his youth.');
